# 使用官方的 Node.js 镜像作为基础镜像
FROM node:20.11.1

# 设置工作目录
WORKDIR /app

# 将 package.json 和 package-lock.json 复制到工作目录
COPY package*.json ./

# 设置 npm 使用阿里云镜像
RUN npm config set registry https://registry.npmmirror.com && npm install

# 复制项目文件到工作目录
COPY . .

# 开放开发服务器的端口
EXPOSE 5173

# 启动开发服务器
CMD ["npm", "run", "serve"]
